# Generated by Django 4.0 on 2022-01-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(upload_to='')),
                ('upload_type', models.CharField(choices=[('ajax', 'ajax'), ('curl', 'curl')], default='ajax', max_length=4)),
                ('dacast_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
